// Central article registry — add new articles here, everything updates automatically
window.TSI_ARTICLES = [
  { slug:'articles/best-income-ideas-uk.html', title:'The 15 Best Ways to Earn a Second Income in the UK for 2026', snippet:'Ranked by earning potential, startup time, and ongoing effort required.', category:'income-ideas', categoryLabel:'Income Ideas', readTime:12, earn:'Up to £2,000/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/second-income-full-time-job-uk.html', title:'How to Build a Second Income Alongside a Full-Time Job', snippet:'Time is the real constraint. These are the strategies that fit around a day job.', category:'income-ideas', categoryLabel:'Income Ideas', readTime:9, earn:'Up to £2,000/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/topcashback-vs-quidco.html', title:'TopCashback vs Quidco: Which Pays More in 2026?', snippet:'We tracked every penny across both platforms. Here is the honest verdict.', category:'cashback', categoryLabel:'Cashback', readTime:8, earn:'£100–£400/yr', featured:false, date:'2026-04-01' },
  { slug:'articles/how-to-maximise-cashback-uk.html', title:'How to Earn Cashback on Almost Everything You Buy', snippet:'A systematic approach that earns the average UK household £200–£500/yr.', category:'cashback', categoryLabel:'Cashback', readTime:7, earn:'£200–£500/yr', featured:false, date:'2026-04-01' },
  { slug:'articles/hmrc-side-hustle-tax-uk.html', title:'Do I Need to Tell HMRC About My Extra Income?', snippet:'The Trading Allowance, Self Assessment, and what triggers a tax bill — plainly explained.', category:'tax', categoryLabel:'Tax & Money', readTime:9, earn:'Could save £1,000s', featured:false, date:'2026-04-01' },
  { slug:'articles/best-paid-surveys-uk.html', title:'Best Paid Survey Sites in the UK for 2026 (Ranked by Pay)', snippet:'Not all survey sites are worth your time. Here are the ones that actually pay well.', category:'income-ideas', categoryLabel:'Income Ideas', readTime:8, earn:'£50–£200/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/freelancing-for-beginners-uk.html', title:'Freelancing for Beginners in the UK: How to Get Your First Client', snippet:"No portfolio needed. Here's exactly how to land your first freelance client.", category:'freelancing', categoryLabel:'Freelancing', readTime:11, earn:'£200–£1,000/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/become-virtual-assistant-uk.html', title:'How to Become a Virtual Assistant in the UK', snippet:'One of the most in-demand and accessible ways to earn extra income — no experience needed.', category:'freelancing', categoryLabel:'Freelancing', readTime:9, earn:'£200–£800/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/selling-on-ebay-uk.html', title:'How to Make Money Selling on eBay in the UK (2026 Guide)', snippet:'From clearing your loft to building a proper reselling business — everything you need.', category:'selling-online', categoryLabel:'Selling Online', readTime:14, earn:'£100–£2,000/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/flipping-items-for-profit-uk.html', title:"How to Make Money Flipping Items in the UK: A Beginner's Guide", snippet:'Buy low, sell high — one of the most reliable ways to turn small capital into consistent income.', category:'selling-online', categoryLabel:'Selling Online', readTime:10, earn:'£200–£1,500/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/selling-on-etsy-uk.html', title:'How to Make Money Selling on Etsy in the UK: 2026 Guide', snippet:'Etsy has millions of buyers and low competition in the right niches — here is how to start.', category:'selling-online', categoryLabel:'Selling Online', readTime:12, earn:'£100–£1,500/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/print-on-demand-uk.html', title:'How to Make Money with Print on Demand in the UK', snippet:'Create designs once, sell them forever — one of the most scalable passive income models.', category:'selling-online', categoryLabel:'Selling Online', readTime:10, earn:'£100–£800/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/rent-out-space-uk.html', title:'How to Make Money Renting Out Space in the UK', snippet:'Your driveway, garage, or spare room could be earning you £50–£500/mo with almost no effort.', category:'income-ideas', categoryLabel:'Income Ideas', readTime:8, earn:'£50–£500/mo', featured:false, date:'2026-04-01' },
  { slug:'articles/investing-small-amounts-uk.html', title:'How to Start Investing Small Amounts of Money in the UK', snippet:"You don't need thousands. Here is how to put even £20/month to work safely.", category:'income-ideas', categoryLabel:'Income Ideas', readTime:10, earn:'Variable', featured:false, date:'2026-04-01' },
  { slug:'articles/matched-betting-guide.html', title:"Is Matched Betting Still Worth It in 2026? A Beginner's Honest Guide", snippet:'Still the most reliable high earner — but requires discipline and the right approach.', category:'high-risk', categoryLabel:'High Risk', readTime:15, earn:'£500–£1,500/mo', featured:false, date:'2026-04-01' }
];

window.TSI_ARTICLE_COUNT = window.TSI_ARTICLES.length;

// Top picks for carousel — update monthly
window.TSI_TOP_PICKS = [
  { title:'TopCashback', subtitle:'Free money on purchases you already make', earn:'£100–£400/yr', difficulty:'Easy', bonus:'🎁 Get £10 free when you sign up', readUrl:'articles/topcashback-vs-quidco.html', signupUrl:'https://www.topcashback.co.uk/ref/member4134008076116', icon:'💳', accentColor:'#c8972a' },
  { title:'Quidco', subtitle:'Cashback on everyday shopping and bills', earn:'£100–£400/yr', difficulty:'Easy', bonus:'🎁 Get £20 bonus after first cashback', readUrl:'articles/topcashback-vs-quidco.html', signupUrl:'https://quidco.com/raf/17840660/', icon:'🛒', accentColor:'#1a6b3a' },
  { title:'Swagbucks', subtitle:'Earn rewards on surveys, videos & shopping', earn:'£20–£60/mo', difficulty:'Easy', bonus:'✓ Free welcome bonus when you join', readUrl:'articles/best-paid-surveys-uk.html', signupUrl:'https://www.swagbucks.com/profile/r_232761491?rp=1', icon:'📋', accentColor:'#4a5568' },
  { title:'Matched Betting', subtitle:'Highest-earning strategy on this site', earn:'£500–£1,500/mo', difficulty:'Medium', bonus:'⚠ High Risk — read the guide first', readUrl:'articles/matched-betting-guide.html', signupUrl:'articles/matched-betting-guide.html', icon:'🎯', accentColor:'#c0392b' }
];
